# Banking Customer & Loan Analytics

## Notebook 1: Python, NumPy & Data Understanding

### Project Objective

The bank wants to understand its customer base, account
portfolio, transaction activity and loan portfolio.

This notebook focuses on understanding the raw banking data
before performing any data cleaning or exploratory analysis.

### Datasets

- Customers
- Accounts
- Transactions
- Loans
- Branches

### Objectives

1. Load the raw datasets
2. Understand dataset structure
3. Inspect columns and data types
4. Identify missing values
5. Identify duplicate records
6. Perform basic numerical profiling using NumPy
7. Establish a data-quality baseline

### Important Principle

No data cleaning or EDA will be performed in this notebook.
The raw datasets will be preserved for the next stage.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully.")

Libraries imported successfully.

## 1. Load Raw Banking Datasets

The project contains five relational datasets representing
customers, accounts, transactions, loans and branches.

The datasets will be loaded without modifying the original data.

In [3]:
customers = pd.read_csv("../data/raw_dataset/customers.csv")
accounts = pd.read_csv("../data/raw_dataset/accounts.csv")
transactions = pd.read_csv("../data/raw_dataset/transactions.csv")
loans = pd.read_csv("../data/raw_dataset/loans.csv")
branches = pd.read_csv("../data/raw_dataset/branches.csv")
("All datasets loaded successfully.")

'All datasets loaded successfully.'

## 2. Check Dataset Size

We will check the number of rows and columns in each dataset.

This helps us understand the scale of the banking data before performing
any cleaning or analysis.

In [4]:
print("Customers:", customers.shape)
print("Accounts:", accounts.shape)
print("Transactions:", transactions.shape)
print("Loans:", loans.shape)
print("Branches:", branches.shape)

Customers: (1002000, 7)
Accounts: (1300000, 6)
Transactions: (5000000, 7)
Loans: (500000, 8)
Branches: (50, 5)

## 3. Create a Reusable Dataset Information Function

Instead of writing the same code repeatedly for every dataset,
we create a reusable function.

The function will show:
- Number of rows
- Number of columns
- Duplicate rows
- Total missing values

In [5]:
def dataset_info(df, name):
    print("\n" + "=" * 55)
    print(name)
    print("=" * 55)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("Duplicate rows:", df.duplicated().sum())
    print("Missing values:", df.isna().sum().sum())

In [6]:
dataset_info(customers, "CUSTOMERS")
dataset_info(accounts, "ACCOUNTS")
dataset_info(transactions, "TRANSACTIONS")
dataset_info(loans, "LOANS")
dataset_info(branches, "BRANCHES")

=======================================================
CUSTOMERS
=======================================================
Rows: 1002000
Columns: 7
Duplicate rows: 2000
Missing values: 4007

=======================================================
ACCOUNTS
=======================================================
Rows: 1300000
Columns: 6
Duplicate rows: 0
Missing values: 0

=======================================================
TRANSACTIONS
=======================================================
Rows: 5000000
Columns: 7
Duplicate rows: 0
Missing values: 0

=======================================================
LOANS
=======================================================
Rows: 500000
Columns: 8
Duplicate rows: 0
Missing values: 0

=======================================================
BRANCHES
=======================================================
Rows: 50
Columns: 5
Duplicate rows: 0
Missing values: 0

## 4. Inspect Dataset Columns

We will inspect the column names of each dataset.

This helps us understand what information is available for customer,
account, transaction, loan, and branch analysis.

In [7]:
print("Customers Columns:")
print(customers.columns.tolist())

print("\nAccounts Columns:")
print(accounts.columns.tolist())

print("\nTransactions Columns:")
print(transactions.columns.tolist())

print("\nLoans Columns:")
print(loans.columns.tolist())

print("\nBranches Columns:")
print(branches.columns.tolist())

Customers Columns:
['CustomerID', 'Age', 'Gender', 'City', 'Occupation', 'Income', 'JoinDate']

Accounts Columns:
['AccountID', 'CustomerID', 'AccountType', 'Balance', 'OpenDate', 'Branch']

Transactions Columns:
['TransactionID', 'AccountID', 'TransactionDate', 'TransactionType', 'Amount', 'Channel', 'Branch']

Loans Columns:
['LoanID', 'CustomerID', 'LoanType', 'LoanAmount', 'InterestRate', 'LoanDate', 'LoanStatus', 'RepaymentAmount']

Branches Columns:
['BranchID', 'BranchName', 'City', 'ManagerExperienceYears', 'OpenDate']

## 5. Preview Customer Data

We will display the first few records of the customer dataset.

This is only for understanding the raw structure.
No transformation or cleaning is performed here.

In [8]:
customers.head()

   CustomerID  Age  Gender       City  Occupation     Income    JoinDate
0           1   38  Female   Lalitpur  Unemployed  100160.69  2023-05-27
1           2   44    Male     Dharan    Salaried   48799.82  2025-05-04
2           3   31    Male    Birgunj     Student  116220.01  2018-01-12
3           4   38    Male    Birgunj     Student   26244.75  2018-08-09
4           5   43    Male  Bharatpur  Unemployed   57600.26  2025-03-18

In [9]:
## 6. Preview Account Data
accounts.head()

   AccountID  CustomerID AccountType    Balance    OpenDate Branch
0    1000001      436452     Savings   59731.28  2021-02-28  BR018
1    1000002      214285     Savings  164506.93  2023-04-06  BR046
2    1000003      279723     Savings  192647.75  2019-02-06  BR001
3    1000004      732562     Savings  133528.07  2021-05-04  BR020
4    1000005      907096      Salary  108520.97  2026-06-23  BR003

In [10]:
## 7. Preview Transaction Data
transactions.head()

,TransactionID,AccountID,TransactionDate,TransactionType,Amount,Channel,Branch
0,1,1433965,2023-09-05,Card Payment,2214.84,ATM,BR017
1,2,2259526,2022-01-19,Withdrawal,9301.66,ATM,BR023
2,3,2275830,2026-01-25,Transfer In,841.43,POS,BR027
3,4,2234514,2022-04-26,Bill Payment,13001.23,POS,BR002
4,5,1168228,2024-01-12,Bill Payment,7831.54,Internet Banking,BR034

In [11]:
## 8. Preview Loan Data
loans.head()

,LoanID,CustomerID,LoanType,LoanAmount,InterestRate,LoanDate,LoanStatus,RepaymentAmount
0,1,974491,Home,652731.51,7.58,2021-06-22,Approved,266193.75
1,2,283305,Business,1439009.61,11.69,2024-07-26,Approved,834606.07
2,3,141195,Home,731314.16,11.99,2025-04-06,Completed,612129.88
3,4,385523,Auto,617687.75,16.17,2025-06-12,Approved,59459.23
4,5,449944,Education,273444.60,9.33,2020-05-03,Completed,181602.79

In [12]:
## 9. Preview Branch Data
branches.head()

  BranchID          BranchName       City  ManagerExperienceYears    OpenDate
0    BR001   Lalitpur Branch 1   Lalitpur                      19  2020-10-26
1    BR002  Dhangadhi Branch 2  Dhangadhi                       6  2008-10-18
2    BR003  Nepalgunj Branch 3  Nepalgunj                      10  2020-04-16
3    BR004     Butwal Branch 4     Butwal                      12  2005-02-21
4    BR005     Butwal Branch 5     Butwal                      13  2020-02-20

## 10. Data Type Inspection

Correct data types are important for reliable analysis.

For example:
- IDs should be treated appropriately
- Amounts should be numeric
- Dates should eventually be converted to datetime
- Categories should be standardized during the cleaning stage

No data type conversion will be performed in this notebook.

In [13]:
print("CUSTOMERS")
print(customers.dtypes)

print("\nACCOUNTS")
print(accounts.dtypes)

print("\nTRANSACTIONS")
print(transactions.dtypes)

print("\nLOANS")
print(loans.dtypes)

print("\nBRANCHES")
print(branches.dtypes)

CUSTOMERS
CustomerID      int64
Age             int64
Gender            str
City              str
Occupation        str
Income        float64
JoinDate          str
dtype: object

ACCOUNTS
AccountID        int64
CustomerID       int64
AccountType        str
Balance        float64
OpenDate           str
Branch             str
dtype: object

TRANSACTIONS
TransactionID        int64
AccountID            int64
TransactionDate        str
TransactionType        str
Amount             float64
Channel                str
Branch                 str
dtype: object

LOANS
LoanID               int64
CustomerID           int64
LoanType               str
LoanAmount         float64
InterestRate       float64
LoanDate               str
LoanStatus             str
RepaymentAmount    float64
dtype: object

BRANCHES
BranchID                    str
BranchName                  str
City                        str
ManagerExperienceYears    int64
OpenDate                    str
dtype: object

## 11. Missing Value Profiling

Before cleaning the datasets, we need to understand whether missing
values exist and where they occur.

The following function calculates:
- Missing count
- Missing percentage

In [14]:
def missing_summary(df):
    result = pd.DataFrame({
        "Missing": df.isna().sum(),
        "Missing %": (df.isna().mean() * 100).round(2)
    })
    
    return result.sort_values("Missing", ascending=False)

In [15]:
missing_summary(customers)

            Missing  Missing %
Occupation     2004        0.2
City           1003        0.1
Income         1000        0.1
Gender            0        0.0
Age               0        0.0
CustomerID        0        0.0
JoinDate          0        0.0

In [16]:
missing_summary(accounts)

             Missing  Missing %
AccountID          0        0.0
CustomerID         0        0.0
AccountType        0        0.0
Balance            0        0.0
OpenDate           0        0.0
Branch             0        0.0

In [17]:
missing_summary(transactions)

                 Missing  Missing %
TransactionID          0        0.0
AccountID              0        0.0
TransactionDate        0        0.0
TransactionType        0        0.0
Amount                 0        0.0
Channel                0        0.0
Branch                 0        0.0

In [18]:
missing_summary(loans)

                 Missing  Missing %
LoanID                 0        0.0
CustomerID             0        0.0
LoanType               0        0.0
LoanAmount             0        0.0
InterestRate           0        0.0
LoanDate               0        0.0
LoanStatus             0        0.0
RepaymentAmount        0        0.0

In [19]:
missing_summary(branches)

                        Missing  Missing %
BranchID                      0        0.0
BranchName                    0        0.0
City                          0        0.0
ManagerExperienceYears        0        0.0
OpenDate                      0        0.0

## 12. Duplicate Record Profiling

Duplicate records can create incorrect customer counts,
transaction totals, loan statistics, and other business metrics.

At this stage, we only identify duplicates.
We will handle them in the Data Cleaning notebook.

In [20]:
print("Customer duplicates:", customers.duplicated().sum())
print("Account duplicates:", accounts.duplicated().sum())
print("Transaction duplicates:", transactions.duplicated().sum())
print("Loan duplicates:", loans.duplicated().sum())
print("Branch duplicates:", branches.duplicated().sum())

Customer duplicates: 2000
Account duplicates: 0
Transaction duplicates: 0
Loan duplicates: 0
Branch duplicates: 0

## 13. Unique Key Profiling

We will check important business keys to understand whether they are
unique and whether duplicate identifiers exist.

Important keys:
- CustomerID
- AccountID
- TransactionID
- LoanID
- Branch

In [21]:
print("CustomerID:")
print("Total:", len(customers))
print("Unique:", customers["CustomerID"].nunique())

print("\nAccountID:")
print("Total:", len(accounts))
print("Unique:", accounts["AccountID"].nunique())

print("\nTransactionID:")
print("Total:", len(transactions))
print("Unique:", transactions["TransactionID"].nunique())

print("\nLoanID:")
print("Total:", len(loans))
print("Unique:", loans["LoanID"].nunique())

print("\nBranch:")
print("Total:", len(branches))
print("Unique:", branches["BranchID"].nunique())

CustomerID:
Total: 1002000
Unique: 1000000

AccountID:
Total: 1300000
Unique: 1300000

TransactionID:
Total: 5000000
Unique: 5000000

LoanID:
Total: 500000
Unique: 500000

Branch:
Total: 50
Unique: 50

## 14. Basic Customer Statistics

We will calculate a few basic numerical statistics to understand the
customer dataset.

These are data-understanding statistics only.
Detailed customer EDA will be performed after data cleaning.

In [22]:
print("Average Age:", customers["Age"].mean())
print("Average Income:", customers["Income"].mean())
print("Total Unique Customers:", customers["CustomerID"].nunique())

Average Age: 36.23558882235529
Average Income: 52341.19411000999
Total Unique Customers: 1000000

## 15. Python Lists

Lists are used to store multiple values in a single variable.

In banking analytics, lists can be useful for storing:
- Important dataset names
- Banking analysis columns
- Account types
- Loan types
- Transaction channels

We will use lists to understand and organize banking information.

In [23]:
banking_datasets = [
    "Customers",
    "Accounts",
    "Transactions",
    "Loans",
    "Branches"
]

print("Banking Datasets:")
print(banking_datasets)

Banking Datasets:
['Customers', 'Accounts', 'Transactions', 'Loans', 'Branches']

## 16. List Indexing

List indexing allows us to access individual elements.

Python uses zero-based indexing, meaning the first element
has index 0.

In [24]:
print("First dataset:", banking_datasets[0])
print("Second dataset:", banking_datasets[1])
print("Last dataset:", banking_datasets[-1])

First dataset: Customers
Second dataset: Accounts
Last dataset: Branches

## 17. List Slicing

List slicing allows us to select a range of elements from a list.

In [25]:
print("First three datasets:", banking_datasets[:3])
print("Last two datasets:", banking_datasets[-2:])

First three datasets: ['Customers', 'Accounts', 'Transactions']
Last two datasets: ['Loans', 'Branches']

## 18. List Methods

We will use common Python list methods to manage banking-related
values.

Important methods include:
- append()
- insert()
- remove()
- pop()
- sort()
- reverse()

In [26]:
account_types = [
    "Savings",
    "Current",
    "Fixed Deposit"
]

print("Original:", account_types)

account_types.append("Salary")
print("After append:", account_types)

account_types.insert(1, "Business")
print("After insert:", account_types)

account_types.remove("Business")
print("After remove:", account_types)

removed_type = account_types.pop()
print("Removed:", removed_type)

print("Final list:", account_types)

Original: ['Savings', 'Current', 'Fixed Deposit']
After append: ['Savings', 'Current', 'Fixed Deposit', 'Salary']
After insert: ['Savings', 'Business', 'Current', 'Fixed Deposit', 'Salary']
After remove: ['Savings', 'Current', 'Fixed Deposit', 'Salary']
Removed: Salary
Final list: ['Savings', 'Current', 'Fixed Deposit']

## 19. Loop Through Banking Datasets

Loops allow us to perform the same operation on multiple datasets
without repeatedly writing the same code.

We will loop through the five banking datasets and display
their names and dimensions.

In [27]:
for name, df in datasets.items():
    print(
        name,
        "->",
        df.shape[0],
        "rows,",
        df.shape[1],
        "columns"
    )

NameError: name 'datasets' is not defined

## 20. Loop Through Dataset Columns

We will use a loop to inspect the columns available in each
banking dataset.

This demonstrates how loops can make repetitive inspection tasks
more efficient.

In [ ]:
for name, df in datasets.items():
    print("\n" + name)
    
    for column in df.columns:
        print("-", column)

Customers
- CustomerID
- Age
- Gender
- City
- Occupation
- Income
- JoinDate

Accounts
- AccountID
- CustomerID
- AccountType
- Balance
- OpenDate
- Branch

Transactions
- TransactionID
- AccountID
- TransactionDate
- TransactionType
- Amount
- Channel
- Branch

Loans
- LoanID
- CustomerID
- LoanType
- LoanAmount
- InterestRate
- LoanDate
- LoanStatus
- RepaymentAmount

Branches
- BranchID
- BranchName
- City
- ManagerExperienceYears
- OpenDate

## 21. Conditional Statements

Conditional statements allow a program to make decisions
based on data values.

We will classify account balances into simple categories.

This is only a Python programming exercise and is not an
EDA-based customer segmentation.

In [ ]:
balance = accounts["Balance"].iloc[0]

if balance >= 100000:
    balance_category = "High Balance"
elif balance >= 50000:
    balance_category = "Medium Balance"
else:
    balance_category = "Low Balance"

print("Account Balance:", balance)
print("Category:", balance_category)

Account Balance: 59731.28
Category: Medium Balance

## 22. Conditional Logic with Loan Amount

We will apply conditional logic to classify a loan amount.

This demonstrates how business rules can be represented
using Python conditional statements.

In [ ]:
loan_amount = loans["LoanAmount"].iloc[0]

if loan_amount >= 1000000:
    loan_category = "High Loan"
elif loan_amount >= 500000:
    loan_category = "Medium Loan"
else:
    loan_category = "Low Loan"

print("Loan Amount:", loan_amount)
print("Loan Category:", loan_category)

Loan Amount: 652731.51
Loan Category: Medium Loan

## 23. Reusable Function

Reusable functions allow us to write a piece of logic once
and use it multiple times.

We will create a function that classifies account balances.

In [ ]:
def classify_balance(balance):
    
    if balance >= 100000:
        return "High Balance"
    
    elif balance >= 50000:
        return "Medium Balance"
    
    else:
        return "Low Balance"

print(classify_balance(150000))
print(classify_balance(75000))
print(classify_balance(25000))

High Balance
Medium Balance
Low Balance

## 24. Reusable Loan Classification Function

We will create another reusable function for classifying
loan amounts.

In [ ]:
def classify_loan(loan_amount):
    
    if loan_amount >= 1000000:
        return "High Loan"
    
    elif loan_amount >= 500000:
        return "Medium Loan"
    
    else:
        return "Low Loan"

print(classify_loan(1500000))
print(classify_loan(750000))
print(classify_loan(250000))

High Loan
Medium Loan
Low Loan

## 25. Python Dictionaries

Dictionaries store data using key-value pairs.

Dictionaries are useful in banking analytics because they can
represent structured information such as dataset names,
column counts, or banking metrics.

In [ ]:
dataset_rows = {
    "Customers": customers.shape[0],
    "Accounts": accounts.shape[0],
    "Transactions": transactions.shape[0],
    "Loans": loans.shape[0],
    "Branches": branches.shape[0]
}

dataset_rows

{'Customers': 1002000,
 'Accounts': 1300000,
 'Transactions': 5000000,
 'Loans': 500000,
 'Branches': 50}

## 26. Access Dictionary Values

We can retrieve individual values from a dictionary using keys.

In [ ]:
print("Customer rows:", dataset_rows["Customers"])
print("Transaction rows:", dataset_rows["Transactions"])
print("Loan rows:", dataset_rows["Loans"])

Customer rows: 1002000
Transaction rows: 5000000
Loan rows: 500000

## 27. Loop Through Dictionary

We can use a loop to process all key-value pairs in a dictionary.

In [ ]:
for dataset_name, row_count in dataset_rows.items():
    print(dataset_name, ":", row_count)

Customers : 1002000
Accounts : 1300000
Transactions : 5000000
Loans : 500000
Branches : 50

## 28. Python Tuples

Tuples are ordered collections that cannot normally be modified
after creation.

They are useful when we want to store fixed groups of values.

For example, we can store the main relationship between two
banking tables as a tuple.

In [ ]:
customer_account_relationship = (
    "Customers",
    "Accounts",
    "CustomerID"
)

customer_account_relationship

('Customers', 'Accounts', 'CustomerID')

## 29. Access Tuple Elements

Tuple elements can be accessed using indexing,
similar to Python lists.

In [ ]:
print("Parent table:", customer_account_relationship[0])
print("Child table:", customer_account_relationship[1])
print("Relationship key:", customer_account_relationship[2])

Parent table: Customers
Child table: Accounts
Relationship key: CustomerID

## 30. Banking Table Relationships

We can store the major relationships between banking tables
using tuples.

These relationships will become important later when performing
Pandas merges and SQL JOIN operations.

In [ ]:
relationships = [
    ("Customers", "Accounts", "CustomerID"),
    ("Accounts", "Transactions", "AccountID"),
    ("Customers", "Loans", "CustomerID"),
    ("Accounts", "Branches", "Branch")
]

for parent, child, key in relationships:
    print(
        parent,
        "->",
        child,
        "using",
        key
    )

Customers -> Accounts using CustomerID
Accounts -> Transactions using AccountID
Customers -> Loans using CustomerID
Accounts -> Branches using Branch

## 31. Python Sets

Sets store unique values.

They are useful in banking analytics when we need to identify
unique cities, account types, transaction channels, or loan types.

In [ ]:
unique_account_types = set(
    accounts["AccountType"].dropna()
)

print("Unique Account Types:")
print(unique_account_types)

Unique Account Types:
{'Salary', 'Fixed Deposit', 'Current', 'Savings'}

## 32. Set Operations

We will demonstrate common set operations using banking
categorical values.

Important operations include:
- Union
- Intersection
- Difference
- Symmetric Difference

In [ ]:
account_types_set = set(
    accounts["AccountType"].dropna()
)

loan_types_set = set(
    loans["LoanType"].dropna()
)

print("Account Types:", account_types_set)
print("Loan Types:", loan_types_set)

print("\nUnion:")
print(account_types_set.union(loan_types_set))

print("\nIntersection:")
print(account_types_set.intersection(loan_types_set))

print("\nAccount Types Difference:")
print(account_types_set.difference(loan_types_set))

print("\nSymmetric Difference:")
print(account_types_set.symmetric_difference(loan_types_set))

Account Types: {'Salary', 'Fixed Deposit', 'Current', 'Savings'}
Loan Types: {'Education', 'Auto', 'Home', 'Business', 'Personal', 'Agriculture'}

Union:
{'Current', 'Education', 'Fixed Deposit', 'Salary', 'Auto', 'Home', 'Business', 'Personal', 'Agriculture', 'Savings'}

Intersection:
set()

Account Types Difference:
{'Salary', 'Current', 'Savings', 'Fixed Deposit'}

Symmetric Difference:
{'Auto', 'Agriculture', 'Current', 'Education', 'Fixed Deposit', 'Salary', 'Home', 'Business', 'Personal', 'Savings'}

## 33. Exception Handling

Exception handling is used to prevent a program from stopping
unexpectedly when an error occurs.

In banking data analysis, exception handling can be useful when:

- Reading datasets
- Converting values
- Performing calculations
- Accessing records
- Handling invalid user input

Python uses try, except, else and finally blocks for exception handling.

In [ ]:
try:
    balance = accounts["Balance"].iloc[0]
    print("Account Balance:", balance)

except Exception as error:
    print("An error occurred:", error)

An error occurred: name 'accounts' is not defined

### 34 Handling a Value Error

A ValueError can occur when a value cannot be converted
to the required data type.

In [ ]:
try:
    loan_amount = float("50000")
    print("Loan Amount:", loan_amount)

except ValueError:
    print("Invalid loan amount.")

Loan Amount: 50000.0

### 34.2 Handling Invalid Numeric Data

The following example demonstrates how invalid numeric
values can be handled safely.

In [ ]:
try:
    amount = float("invalid_amount")
    print("Transaction Amount:", amount)

except ValueError:
    print("Transaction amount is not a valid number.")

Transaction amount is not a valid number.

### 34.3 Handling Missing Dataset Columns

Exception handling can also be used when accessing
a column that may not exist.

In [ ]:
try:
    income_values = customers["Income"]
    print("Income column accessed successfully.")

except KeyError:
    print("Income column does not exist in the dataset.")

Income column accessed successfully.

### 34.4 Using Multiple Exceptions

In [ ]:
try:
    account_id = accounts["AccountID"].iloc[0]
    balance = float(accounts["Balance"].iloc[0])

    print("Account ID:", account_id)
    print("Balance:", balance)

except KeyError:
    print("Required column is missing.")

except IndexError:
    print("No account record is available.")

except ValueError:
    print("Balance contains an invalid numeric value.")

Account ID: 1000001
Balance: 59731.28

### 34.5 Using Finally

The finally block executes whether an exception occurs or not.

In [ ]:
try:
    transaction_amount = float(transactions["Amount"].iloc[0])
    print("Transaction Amount:", transaction_amount)

except (KeyError, IndexError, ValueError) as error:
    print("Error:", error)

finally:
    print("Transaction check completed.")

Transaction Amount: 2214.84
Transaction check completed.

### 34.6 Reusable Function with Exception Handling

A reusable function can combine functions and exception handling
to safely calculate loan exposure.

In [ ]:
def calculate_loan_exposure(loan_amount, repayment_amount):
    try:
        loan_amount = float(loan_amount)
        repayment_amount = float(repayment_amount)

        outstanding = loan_amount - repayment_amount

        if outstanding < 0:
            outstanding = 0

        return outstanding

    except (TypeError, ValueError):
        return None

In [ ]:
print(
    "Outstanding Amount:",
    calculate_loan_exposure(100000, 40000)
)

print(
    "Invalid Input:",
    calculate_loan_exposure("abc", 40000)
)

Outstanding Amount: 60000.0
Invalid Input: None

## 34.7 Exception Handling Validation

Exception handling has been tested using:

- Valid numeric values
- Invalid numeric values
- Missing columns
- Empty record access
- Multiple exception types
- Reusable functions

In [ ]:
print("Exception handling examples completed successfully.")

Exception handling examples completed successfully.

## 35. Python Fundamentals Validation

The Week 1 Python fundamentals requirements have now been covered.

Completed topics:

- Dataset loading
- Dataset inspection
- Data types
- Basic structure
- Lists
- List operations
- Loops
- Conditional statements
- Reusable functions
- Dictionaries
- Tuples
- Sets
- Exception handling

The raw datasets have not been modified.

The next section will begin the NumPy portion of Week 1.

In [ ]:
python_topics_completed = [
    "Dataset Loading",
    "Data Inspection",
    "Data Types",
    "Basic Structure",
    "Lists",
    "Loops",
    "Conditional Statements",
    "Reusable Functions",
    "Dictionaries",
    "Tuples",
    "Sets",
    "Exception Handling"
]

for number, topic in enumerate(
    python_topics_completed,
    start=1
):
    print(f"{number}. {topic} - Completed")

print("\nPython Fundamentals completed successfully.")

1. Dataset Loading - Completed
2. Data Inspection - Completed
3. Data Types - Completed
4. Basic Structure - Completed
5. Lists - Completed
6. Loops - Completed
7. Conditional Statements - Completed
8. Reusable Functions - Completed
9. Dictionaries - Completed
10. Tuples - Completed
11. Sets - Completed
12. Exception Handling - Completed

Python Fundamentals completed successfully.

## 36. NumPy Introduction

NumPy (Numerical Python) is a Python library used for numerical
computations and data analysis.

In this banking project, NumPy will be used to analyze numerical
variables such as:

- Customer Income
- Account Balance
- Loan Amount
- Interest Rate
- Transaction Amount

We will create NumPy arrays from the raw banking data without
modifying the original Pandas DataFrames.

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)
print("NumPy imported successfully.")

NumPy version: 2.5.0
NumPy imported successfully.

## 37. NumPy Arrays

A NumPy array is a collection of values that can be processed
efficiently for numerical calculations.

We will create arrays from important numerical columns in the
banking datasets.

Missing values are excluded only when creating these analysis
arrays. The original datasets remain unchanged.

In [ ]:
income_array = customers["Income"].dropna().to_numpy()

balance_array = accounts["Balance"].dropna().to_numpy()

loan_array = loans["LoanAmount"].dropna().to_numpy()

interest_rate_array = loans["InterestRate"].dropna().to_numpy()

transaction_array = transactions["Amount"].dropna().to_numpy()

print("Income Array:")
print(income_array[:5])

print("\nBalance Array:")
print(balance_array[:5])

print("\nLoan Array:")
print(loan_array[:5])

print("\nInterest Rate Array:")
print(interest_rate_array[:5])

print("\nTransaction Array:")
print(transaction_array[:5])

Income Array:
[100160.69  48799.82 116220.01  26244.75  57600.26]

Balance Array:
[ 59731.28 164506.93 192647.75 133528.07 108520.97]

Loan Array:
[ 652731.51 1439009.61  731314.16  617687.75  273444.6 ]

Interest Rate Array:
[ 7.58 11.69 11.99 16.17  9.33]

Transaction Array:
[ 2214.84  9301.66   841.43 13001.23  7831.54]

## 38. Array Dimensions

The `ndim` attribute tells us the number of dimensions
present in a NumPy array.

The numerical banking arrays created above are one-dimensional
arrays because each represents a single column of values.

In [ ]:
print("Income dimensions:", income_array.ndim)
print("Balance dimensions:", balance_array.ndim)
print("Loan dimensions:", loan_array.ndim)
print("Interest Rate dimensions:", interest_rate_array.ndim)
print("Transaction dimensions:", transaction_array.ndim)

Income dimensions: 1
Balance dimensions: 1
Loan dimensions: 1
Interest Rate dimensions: 1
Transaction dimensions: 1

## 39. Array Shape

The `shape` attribute tells us the size of each dimension
of a NumPy array.

For a one-dimensional array, the shape represents the
number of values contained in the array.

In [ ]:
print("Income shape:", income_array.shape)
print("Balance shape:", balance_array.shape)
print("Loan shape:", loan_array.shape)
print("Interest Rate shape:", interest_rate_array.shape)
print("Transaction shape:", transaction_array.shape)

Income shape: (1001000,)
Balance shape: (1300000,)
Loan shape: (500000,)
Interest Rate shape: (500000,)
Transaction shape: (5000000,)

## 40. Array Indexing

Indexing is used to access individual elements from a NumPy array.

Python uses zero-based indexing, so the first element has index 0.

We will inspect selected values from the banking arrays.

In [ ]:
print("First customer income:", income_array[0])
print("Second customer income:", income_array[1])
print("Last customer income:", income_array[-1])

print("\nFirst account balance:", balance_array[0])
print("Second account balance:", balance_array[1])
print("Last account balance:", balance_array[-1])

print("\nFirst loan amount:", loan_array[0])
print("Second loan amount:", loan_array[1])
print("Last loan amount:", loan_array[-1])

First customer income: 100160.69
Second customer income: 48799.82
Last customer income: 52934.51

First account balance: 59731.28
Second account balance: 164506.93
Last account balance: 113575.03

First loan amount: 652731.51
Second loan amount: 1439009.61
Last loan amount: 912628.34

## 41. Array Slicing

Array slicing allows us to select a range of values from
a NumPy array.

We will display the first five and selected ranges of
banking numerical data.

In [ ]:
print("First 5 customer incomes:")
print(income_array[:5])

print("\nCustomer incomes from index 5 to 9:")
print(income_array[5:10])

print("\nFirst 5 account balances:")
print(balance_array[:5])

print("\nFirst 5 loan amounts:")
print(loan_array[:5])

First 5 customer incomes:
[100160.69  48799.82 116220.01  26244.75  57600.26]

Customer incomes from index 5 to 9:
[45161.76 53891.49 52687.03 82901.96 29035.15]

First 5 account balances:
[ 59731.28 164506.93 192647.75 133528.07 108520.97]

First 5 loan amounts:
[ 652731.51 1439009.61  731314.16  617687.75  273444.6 ]

## 42. Array Operations

NumPy allows mathematical operations to be performed
directly on complete arrays.

We will demonstrate basic operations using loan amounts.

These operations create new arrays and do not modify
the original `loan_array`.

In [ ]:
loan_plus_1000 = loan_array + 1000
loan_minus_1000 = loan_array - 1000
loan_double = loan_array * 2
loan_half = loan_array / 2

print("Original Loan Amounts:")
print(loan_array[:5])

print("\nLoan + 1000:")
print(loan_plus_1000[:5])

print("\nLoan - 1000:")
print(loan_minus_1000[:5])

print("\nLoan × 2:")
print(loan_double[:5])

print("\nLoan ÷ 2:")
print(loan_half[:5])

Original Loan Amounts:
[ 652731.51 1439009.61  731314.16  617687.75  273444.6 ]

Loan + 1000:
[ 653731.51 1440009.61  732314.16  618687.75  274444.6 ]

Loan - 1000:
[ 651731.51 1438009.61  730314.16  616687.75  272444.6 ]

Loan × 2:
[1305463.02 2878019.22 1462628.32 1235375.5   546889.2 ]

Loan ÷ 2:
[326365.755 719504.805 365657.08  308843.875 136722.3  ]


## 43. Average Customer Income

The bank wants to understand the general income level
of its customer base.

We will calculate the average customer income using
NumPy's `mean()` function.

In [ ]:
average_customer_income = np.mean(income_array)

print(
    "Average Customer Income:",
    average_customer_income
)

Average Customer Income: 52341.19411000999

## 44. Average Account Balance

Average account balance provides a baseline understanding
of the amount of money maintained across bank accounts.

We will calculate it using NumPy.

In [ ]:
average_account_balance = np.mean(balance_array)

print(
    "Average Account Balance:",
    average_account_balance
)

Average Account Balance: 123612.01432777691

## 45. Median Loan Amount

The median represents the middle value of the loan amount
distribution.

It is useful because extremely large or small loan values
have less influence on the median than on the average.

In [ ]:
median_loan_amount = np.median(loan_array)

print(
    "Median Loan Amount:",
    median_loan_amount
)

Median Loan Amount: 698801.4299999999

## 46. Maximum and Minimum Loan Amount

We will identify the maximum and minimum loan amounts
present in the raw loan dataset.

These values provide a baseline for identifying unusual
loan values during the Data Cleaning stage.

In [ ]:
maximum_loan_amount = np.max(loan_array)
minimum_loan_amount = np.min(loan_array)

print(
    "Maximum Loan Amount:",
    maximum_loan_amount
)

print(
    "Minimum Loan Amount:",
    minimum_loan_amount
)

Maximum Loan Amount: 30000000.0
Minimum Loan Amount: 50000.0

## 47. Transaction Amount Standard Deviation

Standard deviation measures the amount of variation
or spread in transaction amounts.

A larger standard deviation indicates that transaction
amounts vary more widely around their average.## 47. Transaction Amount Standard Deviation

Standard deviation measures the amount of variation
or spread in transaction amounts.

A larger standard deviation indicates that transaction
amounts vary more widely around their average.

In [ ]:
transaction_standard_deviation = np.std(transaction_array)

print(
    "Transaction Amount Standard Deviation:",
    transaction_standard_deviation
)

Transaction Amount Standard Deviation: 7575.571598732566

## 48. Customer Income Percentiles

Percentiles help us understand different points in the
customer income distribution.

We will calculate:

- 25th percentile
- 50th percentile
- 75th percentile

These values can later support customer segmentation.

In [ ]:
income_25th_percentile = np.percentile(
    income_array,
    25
)

income_50th_percentile = np.percentile(
    income_array,
    50
)

income_75th_percentile = np.percentile(
    income_array,
    75
)

print(
    "25th Percentile:",
    income_25th_percentile
)

print(
    "50th Percentile:",
    income_50th_percentile
)

print(
    "75th Percentile:",
    income_75th_percentile
)

25th Percentile: 31068.63
50th Percentile: 45032.33
75th Percentile: 65204.545

## 49. NumPy Statistical Functions

NumPy provides several statistical functions for numerical analysis.

We will calculate a broader numerical profile for customer income,
account balance, loan amount, and transaction amount.

The following functions will be used:

- mean()
- median()
- min()
- max()
- std()

In [ ]:
print("CUSTOMER INCOME")
print("Mean:", np.mean(income_array))
print("Median:", np.median(income_array))
print("Minimum:", np.min(income_array))
print("Maximum:", np.max(income_array))
print("Standard Deviation:", np.std(income_array))

print("\nACCOUNT BALANCE")
print("Mean:", np.mean(balance_array))
print("Median:", np.median(balance_array))
print("Minimum:", np.min(balance_array))
print("Maximum:", np.max(balance_array))
print("Standard Deviation:", np.std(balance_array))

print("\nLOAN AMOUNT")
print("Mean:", np.mean(loan_array))
print("Median:", np.median(loan_array))
print("Minimum:", np.min(loan_array))
print("Maximum:", np.max(loan_array))
print("Standard Deviation:", np.std(loan_array))

print("\nTRANSACTION AMOUNT")
print("Mean:", np.mean(transaction_array))
print("Median:", np.median(transaction_array))
print("Minimum:", np.min(transaction_array))
print("Maximum:", np.max(transaction_array))
print("Standard Deviation:", np.std(transaction_array))

CUSTOMER INCOME
Mean: 52341.19411000999
Median: 45032.33
Minimum: 12000.0
Maximum: 620226.75
Standard Deviation: 31000.610190093594

ACCOUNT BALANCE
Mean: 123612.01432777691
Median: 74885.25
Minimum: 630.06
Maximum: 8228282.81
Standard Deviation: 162601.54571378246

LOAN AMOUNT
Mean: 1048824.10844054
Median: 698801.4299999999
Minimum: 50000.0
Maximum: 30000000.0
Standard Deviation: 1167702.9140930616

TRANSACTION AMOUNT
Mean: 5773.0382479479995
Median: 3498.68
Minimum: -1.0
Maximum: 500000.0
Standard Deviation: 7575.571598732566

## 50. NumPy Validation

We will validate that the required NumPy calculations
have been successfully completed.

The calculations include:

- Average customer income
- Average account balance
- Median loan amount
- Maximum loan amount
- Minimum loan amount
- Transaction amount standard deviation
- Customer income percentiles

No original banking dataset has been modified.

In [ ]:
numpy_results = {
    "Average Customer Income": average_customer_income,
    "Average Account Balance": average_account_balance,
    "Median Loan Amount": median_loan_amount,
    "Maximum Loan Amount": maximum_loan_amount,
    "Minimum Loan Amount": minimum_loan_amount,
    "Transaction Standard Deviation": transaction_standard_deviation,
    "Income 25th Percentile": income_25th_percentile,
    "Income 50th Percentile": income_50th_percentile,
    "Income 75th Percentile": income_75th_percentile
}

for metric, value in numpy_results.items():
    print(f"{metric}: {value}")

print("\nNumPy analysis completed successfully.")

Average Customer Income: 52341.19411000999
Average Account Balance: 123612.01432777691
Median Loan Amount: 698801.4299999999
Maximum Loan Amount: 30000000.0
Minimum Loan Amount: 50000.0
Transaction Standard Deviation: 7575.571598732566
Income 25th Percentile: 31068.63
Income 50th Percentile: 45032.33
Income 75th Percentile: 65204.545

NumPy analysis completed successfully.